package(
    default_visibility = ["//visibility:public"],
)


cc_library(
    name = "status_util",
    hdrs = ["status_util.h"],
    srcs = ["status_util.cc"],
    deps = [
        "@com_google_leveldb//:leveldb",
        "@com_github_grpc_grpc//:grpc",
        "@com_github_grpc_grpc//:grpc++",
    ],
)
