package(
    default_visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "any_cc_proto",
    deps = ["@com_google_protobuf//:any_proto"],
)

cc_proto_library(
    name = "empty_cc_proto",
    deps = ["@com_google_protobuf//:empty_proto"],
)

cc_proto_library(
    name = "duration_cc_proto",
    deps = ["@com_google_protobuf//:duration_proto"],
)

cc_proto_library(
    name = "timestamp_cc_proto",
    deps = ["@com_google_protobuf//:timestamp_proto"],
)

cc_proto_library(
    name = "wrappers_cc_proto",
    deps = ["@com_google_protobuf//:wrappers_proto"],
)
